/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ShowId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScheduleId = IDL.Nat;
export const Schedule = IDL.Record({
  'id' : ScheduleId,
  'startTime' : IDL.Int,
  'showId' : ShowId,
  'endTime' : IDL.Int,
  'dayOfWeek' : IDL.Text,
});
export const Show = IDL.Record({
  'id' : ShowId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSchedule' : IDL.Func([ShowId, IDL.Int, IDL.Int, IDL.Text], [], []),
  'addShow' : IDL.Func([ShowId, IDL.Text, IDL.Text, ExternalBlob], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSchedule' : IDL.Func([ScheduleId], [], []),
  'deleteShow' : IDL.Func([ShowId], [], []),
  'editSchedule' : IDL.Func(
      [ScheduleId, ShowId, IDL.Int, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'editShow' : IDL.Func([ShowId, IDL.Text, IDL.Text, ExternalBlob], [], []),
  'getAllSchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
  'getAllShows' : IDL.Func([], [IDL.Vec(Show)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSchedulesByDay' : IDL.Func([IDL.Text], [IDL.Vec(Schedule)], ['query']),
  'getSchedulesByShow' : IDL.Func([ShowId], [IDL.Vec(Schedule)], ['query']),
  'getShow' : IDL.Func([ShowId], [Show], ['query']),
  'getUpcomingSchedules' : IDL.Func([IDL.Int], [IDL.Vec(Schedule)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ShowId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScheduleId = IDL.Nat;
  const Schedule = IDL.Record({
    'id' : ScheduleId,
    'startTime' : IDL.Int,
    'showId' : ShowId,
    'endTime' : IDL.Int,
    'dayOfWeek' : IDL.Text,
  });
  const Show = IDL.Record({
    'id' : ShowId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSchedule' : IDL.Func([ShowId, IDL.Int, IDL.Int, IDL.Text], [], []),
    'addShow' : IDL.Func([ShowId, IDL.Text, IDL.Text, ExternalBlob], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSchedule' : IDL.Func([ScheduleId], [], []),
    'deleteShow' : IDL.Func([ShowId], [], []),
    'editSchedule' : IDL.Func(
        [ScheduleId, ShowId, IDL.Int, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'editShow' : IDL.Func([ShowId, IDL.Text, IDL.Text, ExternalBlob], [], []),
    'getAllSchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
    'getAllShows' : IDL.Func([], [IDL.Vec(Show)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSchedulesByDay' : IDL.Func([IDL.Text], [IDL.Vec(Schedule)], ['query']),
    'getSchedulesByShow' : IDL.Func([ShowId], [IDL.Vec(Schedule)], ['query']),
    'getShow' : IDL.Func([ShowId], [Show], ['query']),
    'getUpcomingSchedules' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(Schedule)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };