/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Schedule {
  'id' : ScheduleId,
  'startTime' : bigint,
  'showId' : ShowId,
  'endTime' : bigint,
  'dayOfWeek' : string,
}
export type ScheduleId = bigint;
export interface Show {
  'id' : ShowId,
  'title' : string,
  'description' : string,
  'image' : ExternalBlob,
}
export type ShowId = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSchedule' : ActorMethod<[ShowId, bigint, bigint, string], undefined>,
  'addShow' : ActorMethod<[ShowId, string, string, ExternalBlob], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSchedule' : ActorMethod<[ScheduleId], undefined>,
  'deleteShow' : ActorMethod<[ShowId], undefined>,
  'editSchedule' : ActorMethod<
    [ScheduleId, ShowId, bigint, bigint, string],
    undefined
  >,
  'editShow' : ActorMethod<[ShowId, string, string, ExternalBlob], undefined>,
  'getAllSchedules' : ActorMethod<[], Array<Schedule>>,
  'getAllShows' : ActorMethod<[], Array<Show>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSchedulesByDay' : ActorMethod<[string], Array<Schedule>>,
  'getSchedulesByShow' : ActorMethod<[ShowId], Array<Schedule>>,
  'getShow' : ActorMethod<[ShowId], Show>,
  'getUpcomingSchedules' : ActorMethod<[bigint], Array<Schedule>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];